=== sampig/XMLDB/Practical_XML/Exercise04/personalschedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
    jaxb:version="2.0">
    <xs:element name="TerminCalendar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="schedule" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="year" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="month" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="day" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="entry" type="entryType"
                                                                    minOccurs="0" maxOccurs="unbounded" />
                                                            </xs:sequence>
                                                            <xs:attribute name="n">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:integer">
                                                                        <xs:minInclusive value="1" />
                                                                        <xs:maxInclusive value="31" />
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="n">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1" />
                                                            <xs:maxInclusive value="12" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="n" type="xs:gYear" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="entryType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="location" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="starttime" type="xs:time" />
        <xs:attribute name="duration" type="xs:duration" />
    </xs:complexType>
</xs:schema>

=== sampig/XMLDB/Practical_XML/Exercise04/personalschedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<TerminCalendar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="personalschedule.xsd">
    <schedule name="Chenfeng Zhu">
        <year n="2017">
            <month n="2">
                <day n="3">
                    <entry starttime="11:00:00" duration="PT01H30M">
                        <name>XML lab meeting</name>
                        <description>This is a meeting for exercise 04.</description>
                        <location>CIP Room</location>
                    </entry>
                </day>
                <day n="14">
                    <entry starttime="14:00:00" duration="PT02H">
                        <name>DS Exam</name>
                    </entry>
                </day>
            </month>
            <month n="3">
                <day n="2">
                    <entry starttime="11:00:00" duration="PT45M">
                        <name>SDF Exam</name>
                    </entry>
                </day>
            </month>
        </year>
    </schedule>
</TerminCalendar>
